apiVersion: apps/v1
kind: Deployment
metadata:
  # set your lab user name
  name: user17-hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      # set your lab user name
      app: user17-hello-world
  template:
    metadata:
      labels:
        # set your lab user name
        app: user17-hello-world
    spec:
      containers:
        - name: hello-world
          image: "quay.io/desalen/quaydannyrepo:v2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10